version: '3.8'

services:
  # Имя сервиса изменено для отражения запускаемого бота
  librusec_bot: 
    # Имя контейнера
    container_name: librusec-base-bot # Изменено для ясности
    # Собираем образ из Dockerfile в текущей папке
    build: .
    restart: always
    
    # Команда для запуска
    command: ["python", "Librusec_bot.py"]
    
    volumes:
      # 1. Монтируем папку с ЛИБРУСЕК библиотекой на /app/books в контейнере
      - E:/Books/_Lib.rus.ec - Официальная:/app/books:ro 
      # 2. Монтируем папку для данных (логи, downloads) на /app/data
      - E:/Books/BotsTG:/app/data:rw 
      
    environment:
      # Теперь используется токен Librusec
      BOT_TOKEN: ${LIBRUSEC_TOKEN} 
      ADMIN_IDS: ${ADMIN_IDS}
      
      # Путь INPX внутри контейнера
      INPX_FILE: /app/books/librusec_local_fb2.inpx 
      BOOKS_DIR: /app/books
      LOG_FILE: /app/data/Log_librusecBase_bot.log
      # Остальные пути, если они используются в коде
      READER_FOLDER: /app/data/reader
      DOWNLOAD_FOLDER: /app/data/downloads
      USERS_JSON_FILE: /app/data/users_librusec.json
      DB_FILE: /app/data/reader_data_librusec.db